/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Fri Feb 16 13:37:45 2018. */

#ifndef PB_AT_AC_TUWIEN_IOT1718_SENSORDATA_PB_H_INCLUDED
#define PB_AT_AC_TUWIEN_IOT1718_SENSORDATA_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _at_ac_tuwien_iot1718_Command_CommandType {
    at_ac_tuwien_iot1718_Command_CommandType_NEW_UPDATE_INTERVAL = 1
} at_ac_tuwien_iot1718_Command_CommandType;
#define _at_ac_tuwien_iot1718_Command_CommandType_MIN at_ac_tuwien_iot1718_Command_CommandType_NEW_UPDATE_INTERVAL
#define _at_ac_tuwien_iot1718_Command_CommandType_MAX at_ac_tuwien_iot1718_Command_CommandType_NEW_UPDATE_INTERVAL
#define _at_ac_tuwien_iot1718_Command_CommandType_ARRAYSIZE ((at_ac_tuwien_iot1718_Command_CommandType)(at_ac_tuwien_iot1718_Command_CommandType_NEW_UPDATE_INTERVAL+1))

typedef enum _at_ac_tuwien_iot1718_N2C_SensorType {
    at_ac_tuwien_iot1718_N2C_SensorType_TEMPERATURE = 1,
    at_ac_tuwien_iot1718_N2C_SensorType_HUMIDITY = 2
} at_ac_tuwien_iot1718_N2C_SensorType;
#define _at_ac_tuwien_iot1718_N2C_SensorType_MIN at_ac_tuwien_iot1718_N2C_SensorType_TEMPERATURE
#define _at_ac_tuwien_iot1718_N2C_SensorType_MAX at_ac_tuwien_iot1718_N2C_SensorType_HUMIDITY
#define _at_ac_tuwien_iot1718_N2C_SensorType_ARRAYSIZE ((at_ac_tuwien_iot1718_N2C_SensorType)(at_ac_tuwien_iot1718_N2C_SensorType_HUMIDITY+1))

/* Struct definitions */
typedef struct _at_ac_tuwien_iot1718_Command {
    at_ac_tuwien_iot1718_Command_CommandType type;
    bool has_param1;
    uint32_t param1;
    bool has_param2;
    uint32_t param2;
    bool has_param3;
    uint32_t param3;
/* @@protoc_insertion_point(struct:at_ac_tuwien_iot1718_Command) */
} at_ac_tuwien_iot1718_Command;

typedef struct _at_ac_tuwien_iot1718_N2C {
    uint32_t timestamp;
    uint32_t roomNo;
    at_ac_tuwien_iot1718_N2C_SensorType type;
    uint32_t data;
/* @@protoc_insertion_point(struct:at_ac_tuwien_iot1718_N2C) */
} at_ac_tuwien_iot1718_N2C;

typedef struct _at_ac_tuwien_iot1718_C2N {
    uint32_t timestamp;
    bool has_command;
    at_ac_tuwien_iot1718_Command command;
/* @@protoc_insertion_point(struct:at_ac_tuwien_iot1718_C2N) */
} at_ac_tuwien_iot1718_C2N;

/* Default values for struct fields */

/* Initializer values for message structs */
#define at_ac_tuwien_iot1718_Command_init_default {_at_ac_tuwien_iot1718_Command_CommandType_MIN, false, 0, false, 0, false, 0}
#define at_ac_tuwien_iot1718_N2C_init_default    {0, 0, _at_ac_tuwien_iot1718_N2C_SensorType_MIN, 0}
#define at_ac_tuwien_iot1718_C2N_init_default    {0, false, at_ac_tuwien_iot1718_Command_init_default}
#define at_ac_tuwien_iot1718_Command_init_zero   {_at_ac_tuwien_iot1718_Command_CommandType_MIN, false, 0, false, 0, false, 0}
#define at_ac_tuwien_iot1718_N2C_init_zero       {0, 0, _at_ac_tuwien_iot1718_N2C_SensorType_MIN, 0}
#define at_ac_tuwien_iot1718_C2N_init_zero       {0, false, at_ac_tuwien_iot1718_Command_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define at_ac_tuwien_iot1718_Command_type_tag    1
#define at_ac_tuwien_iot1718_Command_param1_tag  2
#define at_ac_tuwien_iot1718_Command_param2_tag  3
#define at_ac_tuwien_iot1718_Command_param3_tag  4
#define at_ac_tuwien_iot1718_N2C_timestamp_tag   1
#define at_ac_tuwien_iot1718_N2C_roomNo_tag      2
#define at_ac_tuwien_iot1718_N2C_type_tag        3
#define at_ac_tuwien_iot1718_N2C_data_tag        4
#define at_ac_tuwien_iot1718_C2N_timestamp_tag   1
#define at_ac_tuwien_iot1718_C2N_command_tag     2

/* Struct field encoding specification for nanopb */
extern const pb_field_t at_ac_tuwien_iot1718_Command_fields[5];
extern const pb_field_t at_ac_tuwien_iot1718_N2C_fields[5];
extern const pb_field_t at_ac_tuwien_iot1718_C2N_fields[3];

/* Maximum encoded size of messages (where known) */
#define at_ac_tuwien_iot1718_Command_size        17
#define at_ac_tuwien_iot1718_N2C_size            17
#define at_ac_tuwien_iot1718_C2N_size            24

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SENSORDATA_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
